import type { PluginCategoryConfig, PluginMetadata } from "../types";

export const pluginCategories: PluginCategoryConfig[] = [
  {
    id: "synth",
    name: "Synths",
    description:
      "Virtual instruments and soft synth engines for bass, lead, and chord design.",
    hostSupport: ["Ableton", "FL Studio", "LocalHost"],
  },
  {
    id: "vocal",
    name: "Vocal Processors",
    description: "Vocal tuning, harmonizers, and vocal production processors.",
    hostSupport: ["Ableton", "FL Studio", "LocalHost"],
  },
  {
    id: "sampler",
    name: "Samplers",
    description: "Sample-based instruments and granular playback engines.",
    hostSupport: ["Ableton", "FL Studio", "LocalHost"],
  },
  {
    id: "mixing",
    name: "Mixing & Mastering",
    description: "Dynamics, stereo imaging, and final polish plugins.",
    hostSupport: ["Ableton", "FL Studio", "LocalHost"],
  },
  {
    id: "creative",
    name: "Creative FX",
    description: "Special FX, modulators, and sonic sculpting tools.",
    hostSupport: ["Ableton", "FL Studio", "LocalHost"],
  },
  {
    id: "utility",
    name: "Workflow Utilities",
    description:
      "Session tools, tempo managers, and bridge utilities for DAW integration.",
    hostSupport: ["Ableton", "FL Studio", "LocalHost"],
  },
];

export const pluginDefinitions: PluginMetadata[] = [
  {
    id: "serumWave",
    name: "SerumWave",
    vendor: "NeonLabs",
    category: "synth",
    description:
      "A modern wavetable synth with aggressive modulation and polished stage-ready tone.",
    hostSupport: ["Ableton", "FL Studio", "LocalHost"],
    defaultPresetId: "serumWaveToplineLead",
    parameters: [
      {
        id: "oscillatorBlend",
        name: "Oscillator Blend",
        min: 0,
        max: 100,
        default: 72,
        unit: "%",
        automationCapable: true,
      },
      {
        id: "filterCutoff",
        name: "Filter Cutoff",
        min: 20,
        max: 20000,
        default: 1400,
        unit: "Hz",
        automationCapable: true,
      },
      {
        id: "ampAttack",
        name: "Amp Attack",
        min: 0,
        max: 500,
        default: 12,
        unit: "ms",
        automationCapable: true,
      },
      {
        id: "modDepth",
        name: "Mod Depth",
        min: 0,
        max: 100,
        default: 54,
        unit: "%",
        automationCapable: true,
      },
    ],
    presets: [
      {
        id: "serumWaveToplineLead",
        name: "Topline Lead",
        description:
          "Bright lead with wide filter movement for club-ready synth hooks.",
        parameterValues: {
          oscillatorBlend: 72,
          filterCutoff: 1350,
          ampAttack: 12,
          modDepth: 54,
        },
      },
      {
        id: "serumWaveBassWarm",
        name: "Warm Bass",
        description:
          "Low-end sub warmth with a smooth filter envelope for basslines.",
        parameterValues: {
          oscillatorBlend: 92,
          filterCutoff: 520,
          ampAttack: 8,
          modDepth: 26,
        },
      },
    ],
    routing: {
      source: "MIDI",
      destination: "Instrument Rack",
      insertPoint: "Synth Chain",
      sends: ["ChorusSend", "ReverbSend"],
    },
    automationBindings: [
      {
        id: "serumWaveFilterSweep",
        name: "Filter Sweep",
        parameterId: "filterCutoff",
        controlSource: "Macro",
        curve: "sine",
        range: { min: 200, max: 1800 },
      },
    ],
    bridgeSupport: true,
  },
  {
    id: "hyperNova",
    name: "HyperNova",
    vendor: "PhaseForge",
    category: "synth",
    description:
      "Analog-inspired synth with fast modulation and lush pad textures.",
    hostSupport: ["Ableton", "FL Studio", "LocalHost"],
    defaultPresetId: "hyperNovaDreamPad",
    parameters: [
      {
        id: "oscShape",
        name: "Oscillator Shape",
        min: 0,
        max: 100,
        default: 48,
        unit: "%",
        automationCapable: true,
      },
      {
        id: "filterResonance",
        name: "Filter Resonance",
        min: 0,
        max: 100,
        default: 24,
        unit: "%",
        automationCapable: true,
      },
      {
        id: "envRelease",
        name: "Envelope Release",
        min: 0,
        max: 1500,
        default: 560,
        unit: "ms",
        automationCapable: true,
      },
    ],
    presets: [
      {
        id: "hyperNovaDreamPad",
        name: "Dream Pad",
        description: "Wide pad with slow motion filter and gentle motion.",
        parameterValues: { oscShape: 48, filterResonance: 24, envRelease: 560 },
      },
      {
        id: "hyperNovaPulse",
        name: "Pulse Bass",
        description:
          "Pulsing low-end synth with tight attack and controlled resonance.",
        parameterValues: { oscShape: 86, filterResonance: 62, envRelease: 180 },
      },
    ],
    routing: {
      source: "MIDI",
      destination: "Instrument Rack",
      insertPoint: "Pad / Bass Layer",
      sends: ["DelaySend", "ReverbSend"],
    },
    automationBindings: [
      {
        id: "hyperNovaResonanceMorph",
        name: "Resonance Morph",
        parameterId: "filterResonance",
        controlSource: "LFO",
        curve: "log",
        range: { min: 10, max: 80 },
      },
    ],
    bridgeSupport: true,
  },
  {
    id: "polyDream",
    name: "PolyDream",
    vendor: "Chromatic Labs",
    category: "synth",
    description:
      "A polyphonic synth engine designed for lush chords and cinematic textures.",
    hostSupport: ["Ableton", "FL Studio", "LocalHost"],
    defaultPresetId: "polyDreamChords",
    parameters: [
      {
        id: "voiceStack",
        name: "Voice Stack",
        min: 1,
        max: 12,
        default: 5,
        unit: "voices",
        automationCapable: true,
      },
      {
        id: "filterCutoff",
        name: "Filter Cutoff",
        min: 20,
        max: 20000,
        default: 900,
        unit: "Hz",
        automationCapable: true,
      },
      {
        id: "chorusDepth",
        name: "Chorus Depth",
        min: 0,
        max: 100,
        default: 62,
        unit: "%",
        automationCapable: true,
      },
    ],
    presets: [
      {
        id: "polyDreamChords",
        name: "Chord Motion",
        description: "Lush chord engine with moving filter and stereo width.",
        parameterValues: { voiceStack: 7, filterCutoff: 900, chorusDepth: 62 },
      },
      {
        id: "polyDreamArp",
        name: "Arp Sequence",
        description:
          "Fast arpeggiated sequence with smooth filter and modulation.",
        parameterValues: { voiceStack: 4, filterCutoff: 1200, chorusDepth: 30 },
      },
    ],
    routing: {
      source: "MIDI",
      destination: "Instrument Rack",
      insertPoint: "Chord Section",
      sends: ["PlateSend", "ReverbSend"],
    },
    automationBindings: [
      {
        id: "polyDreamWidthSweep",
        name: "Stereo Width Sweep",
        parameterId: "chorusDepth",
        controlSource: "Macro",
        curve: "linear",
        range: { min: 10, max: 90 },
      },
    ],
    bridgeSupport: true,
  },
  {
    id: "vocalTunePro",
    name: "VocalTune Pro",
    vendor: "VoxTech",
    category: "vocal",
    description:
      "Pitch correction and vocal shaping for polished lead vocals and harmonies.",
    hostSupport: ["Ableton", "FL Studio", "LocalHost"],
    defaultPresetId: "vocalTuneProLead",
    parameters: [
      {
        id: "pitchCorrection",
        name: "Pitch Correction",
        min: 0,
        max: 100,
        default: 72,
        unit: "%",
        automationCapable: true,
      },
      {
        id: "formantShift",
        name: "Formant Shift",
        min: -12,
        max: 12,
        default: 0,
        unit: "semitones",
        automationCapable: true,
      },
      {
        id: "dryWet",
        name: "Dry/Wet",
        min: 0,
        max: 100,
        default: 40,
        unit: "%",
        automationCapable: true,
      },
    ],
    presets: [
      {
        id: "vocalTuneProLead",
        name: "Lead Vocal",
        description: "Transparent pitch correction with natural body.",
        parameterValues: { pitchCorrection: 72, formantShift: 0, dryWet: 40 },
      },
      {
        id: "vocalTuneProHarmony",
        name: "Harmony Stack",
        description: "Rich harmonic doubling with formant enhancement.",
        parameterValues: { pitchCorrection: 60, formantShift: 2, dryWet: 55 },
      },
    ],
    routing: {
      source: "Audio In",
      destination: "Vocal Chain",
      insertPoint: "Vocal FX Rack",
      sends: ["DelaySend", "PlateSend"],
    },
    automationBindings: [
      {
        id: "vocalTuneProFormantSweep",
        name: "Formant Sweep",
        parameterId: "formantShift",
        controlSource: "MIDI CC",
        curve: "step",
        range: { min: -4, max: 6 },
      },
    ],
    bridgeSupport: true,
  },
  {
    id: "harmonyLab",
    name: "HarmonyLab",
    vendor: "ChordCore",
    category: "vocal",
    description:
      "Harmony generator with vocal doubler and intelligent pitch stacking.",
    hostSupport: ["Ableton", "FL Studio", "LocalHost"],
    defaultPresetId: "harmonyLabClassic",
    parameters: [
      {
        id: "harmonyDepth",
        name: "Harmony Depth",
        min: 0,
        max: 100,
        default: 64,
        unit: "%",
        automationCapable: true,
      },
      {
        id: "blend",
        name: "Blend",
        min: 0,
        max: 100,
        default: 48,
        unit: "%",
        automationCapable: true,
      },
    ],
    presets: [
      {
        id: "harmonyLabClassic",
        name: "Classic Harmony",
        description: "Natural harmonies with gentle detune and depth.",
        parameterValues: { harmonyDepth: 64, blend: 48 },
      },
      {
        id: "harmonyLabWide",
        name: "Wide Vocal Stack",
        description: "Rich stacked harmonies designed for modern pop.",
        parameterValues: { harmonyDepth: 82, blend: 72 },
      },
    ],
    routing: {
      source: "Audio In",
      destination: "Vocal Chain",
      insertPoint: "Harmony Stack",
      sends: ["ReverbSend"],
    },
    automationBindings: [
      {
        id: "harmonyLabDepthMod",
        name: "Harmony Depth Mod",
        parameterId: "harmonyDepth",
        controlSource: "Envelope",
        curve: "linear",
        range: { min: 20, max: 100 },
      },
    ],
    bridgeSupport: true,
  },
  {
    id: "sampleNest",
    name: "SampleNest",
    vendor: "LoopLayer",
    category: "sampler",
    description:
      "A flexible sampler engine for one-shots, loops, and layered sample playback.",
    hostSupport: ["Ableton", "FL Studio", "LocalHost"],
    defaultPresetId: "sampleNestTrapKit",
    parameters: [
      {
        id: "sampleStart",
        name: "Sample Start",
        min: 0,
        max: 100,
        default: 12,
        unit: "%",
        automationCapable: true,
      },
      {
        id: "sampleLength",
        name: "Sample Length",
        min: 1,
        max: 100,
        default: 82,
        unit: "%",
        automationCapable: true,
      },
      {
        id: "loopMode",
        name: "Loop Mode",
        min: 0,
        max: 2,
        default: 1,
        unit: "mode",
        automationCapable: false,
      },
    ],
    presets: [
      {
        id: "sampleNestTrapKit",
        name: "Trap Kit",
        description: "Punchy sample playback optimized for trap drum racks.",
        parameterValues: { sampleStart: 12, sampleLength: 82, loopMode: 1 },
      },
      {
        id: "sampleNestAmbient",
        name: "Ambient Texture",
        description: "Soft sample loops with long tails and wide spread.",
        parameterValues: { sampleStart: 5, sampleLength: 94, loopMode: 2 },
      },
    ],
    routing: {
      source: "Sample Bank",
      destination: "Sampler Rack",
      insertPoint: "Layered Sampler",
      sends: ["ReverbSend", "DelaySend"],
    },
    automationBindings: [
      {
        id: "sampleNestStartSweep",
        name: "Sample Start Sweep",
        parameterId: "sampleStart",
        controlSource: "Macro",
        curve: "linear",
        range: { min: 0, max: 40 },
      },
    ],
    bridgeSupport: true,
  },
  {
    id: "drumVault",
    name: "DrumVault",
    vendor: "BeatEngine",
    category: "sampler",
    description:
      "Drum sampler optimized for one-shot layering, live triggering, and pattern launch workflows.",
    hostSupport: ["Ableton", "FL Studio", "LocalHost"],
    defaultPresetId: "drumVaultTightKit",
    parameters: [
      {
        id: "velocityCurve",
        name: "Velocity Curve",
        min: 0,
        max: 100,
        default: 58,
        unit: "%",
        automationCapable: true,
      },
      {
        id: "filterResonance",
        name: "Filter Resonance",
        min: 0,
        max: 100,
        default: 20,
        unit: "%",
        automationCapable: true,
      },
      {
        id: "panSpread",
        name: "Pan Spread",
        min: 0,
        max: 100,
        default: 16,
        unit: "%",
        automationCapable: true,
      },
    ],
    presets: [
      {
        id: "drumVaultTightKit",
        name: "Tight Kit",
        description: "Punchy drum kit with fast transient shaping.",
        parameterValues: {
          velocityCurve: 58,
          filterResonance: 20,
          panSpread: 16,
        },
      },
      {
        id: "drumVaultVintage",
        name: "Vintage Drum Rack",
        description: "Warm sampled drums with analog-style movement.",
        parameterValues: {
          velocityCurve: 72,
          filterResonance: 34,
          panSpread: 28,
        },
      },
    ],
    routing: {
      source: "MIDI/Note",
      destination: "Drum Bus",
      insertPoint: "Drum Rack",
      sends: ["SaturationSend", "ReverbSend"],
    },
    automationBindings: [
      {
        id: "drumVaultVelocityMorph",
        name: "Velocity Morph",
        parameterId: "velocityCurve",
        controlSource: "MIDI CC",
        curve: "step",
        range: { min: 10, max: 90 },
      },
    ],
    bridgeSupport: true,
  },
  {
    id: "glueBus",
    name: "GlueBus",
    vendor: "MixLab",
    category: "mixing",
    description:
      "A bus compressor and glue module designed for punchy group dynamics.",
    hostSupport: ["Ableton", "FL Studio", "LocalHost"],
    defaultPresetId: "glueBusPunch",
    parameters: [
      {
        id: "threshold",
        name: "Threshold",
        min: -60,
        max: 0,
        default: -18,
        unit: "dB",
        automationCapable: true,
      },
      {
        id: "ratio",
        name: "Ratio",
        min: 1,
        max: 20,
        default: 4,
        unit: ":1",
        automationCapable: true,
      },
      {
        id: "makeupGain",
        name: "Makeup Gain",
        min: 0,
        max: 12,
        default: 3,
        unit: "dB",
        automationCapable: true,
      },
    ],
    presets: [
      {
        id: "glueBusPunch",
        name: "Punch Bus",
        description: "Fast glue compression for synth and drum groups.",
        parameterValues: { threshold: -18, ratio: 4, makeupGain: 3 },
      },
      {
        id: "glueBusWarm",
        name: "Warm Mix",
        description: "Gentle bus compression for full mixes and stems.",
        parameterValues: { threshold: -24, ratio: 2.5, makeupGain: 2 },
      },
    ],
    routing: {
      source: "Group Bus",
      destination: "Master Bus",
      insertPoint: "Mix Group",
      sends: ["ParallelSend"],
    },
    automationBindings: [
      {
        id: "glueBusThresholdRide",
        name: "Threshold Ride",
        parameterId: "threshold",
        controlSource: "Envelope",
        curve: "log",
        range: { min: -28, max: -12 },
      },
    ],
    bridgeSupport: true,
  },
  {
    id: "multibandMaxima",
    name: "Multiband Maxima",
    vendor: "MasterCore",
    category: "mixing",
    description:
      "Multiband processor for transparent mastering and stereo balance.",
    hostSupport: ["Ableton", "FL Studio", "LocalHost"],
    defaultPresetId: "multibandMaximaMaster",
    parameters: [
      {
        id: "lowGain",
        name: "Low Gain",
        min: -12,
        max: 12,
        default: 1.2,
        unit: "dB",
        automationCapable: true,
      },
      {
        id: "midGain",
        name: "Mid Gain",
        min: -12,
        max: 12,
        default: 0.4,
        unit: "dB",
        automationCapable: true,
      },
      {
        id: "highGain",
        name: "High Gain",
        min: -12,
        max: 12,
        default: 1.8,
        unit: "dB",
        automationCapable: true,
      },
    ],
    presets: [
      {
        id: "multibandMaximaMaster",
        name: "Master Sculpt",
        description: "Balanced multiband shaping for finished stems.",
        parameterValues: { lowGain: 1.2, midGain: 0.4, highGain: 1.8 },
      },
    ],
    routing: {
      source: "Stereo Bus",
      destination: "Master Channel",
      insertPoint: "Master Chain",
      sends: ["LimiterSend"],
    },
    automationBindings: [
      {
        id: "multibandMaximaHighRide",
        name: "High Band Ride",
        parameterId: "highGain",
        controlSource: "Macro",
        curve: "linear",
        range: { min: -3, max: 6 },
      },
    ],
    bridgeSupport: true,
  },
  {
    id: "spaceDelay",
    name: "SpaceDelay",
    vendor: "EchoForge",
    category: "creative",
    description:
      "A creative delay engine with tempo-synced modulation and spatial feedback.",
    hostSupport: ["Ableton", "FL Studio", "LocalHost"],
    defaultPresetId: "spaceDelayWide",
    parameters: [
      {
        id: "feedback",
        name: "Feedback",
        min: 0,
        max: 100,
        default: 43,
        unit: "%",
        automationCapable: true,
      },
      {
        id: "delayTime",
        name: "Delay Time",
        min: 10,
        max: 1200,
        default: 320,
        unit: "ms",
        automationCapable: true,
      },
      {
        id: "wetDry",
        name: "Wet/Dry",
        min: 0,
        max: 100,
        default: 35,
        unit: "%",
        automationCapable: true,
      },
    ],
    presets: [
      {
        id: "spaceDelayWide",
        name: "Wide Atmosphere",
        description: "Large stereo delay with diffuse tails.",
        parameterValues: { feedback: 43, delayTime: 320, wetDry: 35 },
      },
    ],
    routing: {
      source: "Insert",
      destination: "Aux Return",
      insertPoint: "FX Bus",
      sends: ["ReverbSend"],
    },
    automationBindings: [
      {
        id: "spaceDelayFeedbackLFO",
        name: "Feedback LFO",
        parameterId: "feedback",
        controlSource: "LFO",
        curve: "sine",
        range: { min: 10, max: 70 },
      },
    ],
    bridgeSupport: true,
  },
  {
    id: "morphVerb",
    name: "MorphVerb",
    vendor: "ReverbLab",
    category: "creative",
    description:
      "An evolving reverb engine for dreamy ambient tails and spectral movement.",
    hostSupport: ["Ableton", "FL Studio", "LocalHost"],
    defaultPresetId: "morphVerbDream",
    parameters: [
      {
        id: "decay",
        name: "Decay",
        min: 100,
        max: 9000,
        default: 1820,
        unit: "ms",
        automationCapable: true,
      },
      {
        id: "modDepth",
        name: "Mod Depth",
        min: 0,
        max: 100,
        default: 65,
        unit: "%",
        automationCapable: true,
      },
      {
        id: "size",
        name: "Room Size",
        min: 0,
        max: 100,
        default: 86,
        unit: "%",
        automationCapable: true,
      },
    ],
    presets: [
      {
        id: "morphVerbDream",
        name: "Dream Reverb",
        description: "Smooth ambient reverb with deep movement.",
        parameterValues: { decay: 1820, modDepth: 65, size: 86 },
      },
    ],
    routing: {
      source: "Insert",
      destination: "Reverb Bus",
      insertPoint: "FX Return",
      sends: ["ParallelSend"],
    },
    automationBindings: [
      {
        id: "morphVerbModDepth",
        name: "Mod Depth Ride",
        parameterId: "modDepth",
        controlSource: "Macro",
        curve: "sine",
        range: { min: 20, max: 90 },
      },
    ],
    bridgeSupport: true,
  },
  {
    id: "clipLauncher",
    name: "ClipLauncher",
    vendor: "WorkflowOne",
    category: "utility",
    description:
      "A session arranger utility that mirrors clips and sets for DAW bridge workflows.",
    hostSupport: ["Ableton", "FL Studio", "LocalHost"],
    defaultPresetId: "clipLauncherLive",
    parameters: [
      {
        id: "clipSync",
        name: "Clip Sync",
        min: 0,
        max: 100,
        default: 100,
        unit: "%",
        automationCapable: false,
      },
      {
        id: "launchQuantize",
        name: "Launch Quantize",
        min: 0,
        max: 128,
        default: 16,
        unit: "ticks",
        automationCapable: false,
      },
    ],
    presets: [
      {
        id: "clipLauncherLive",
        name: "Live Clip Flow",
        description: "Preset for session performance and DAW clip launching.",
        parameterValues: { clipSync: 100, launchQuantize: 16 },
      },
    ],
    routing: {
      source: "Session View",
      destination: "DAW Host",
      insertPoint: "Utility Rack",
      sends: [],
    },
    automationBindings: [
      {
        id: "clipLauncherQuantize",
        name: "Launch Quantize",
        parameterId: "launchQuantize",
        controlSource: "Macro",
        curve: "step",
        range: { min: 1, max: 32 },
      },
    ],
    bridgeSupport: true,
  },
  {
    id: "tempoLock",
    name: "TempoLock",
    vendor: "SyncWorks",
    category: "utility",
    description:
      "Tempo manager and BPM lock utility for cross-DAW timing consistency.",
    hostSupport: ["Ableton", "FL Studio", "LocalHost"],
    defaultPresetId: "tempoLockDefault",
    parameters: [
      {
        id: "tempo",
        name: "Tempo",
        min: 60,
        max: 200,
        default: 124,
        unit: "BPM",
        automationCapable: true,
      },
      {
        id: "swing",
        name: "Swing",
        min: 0,
        max: 100,
        default: 12,
        unit: "%",
        automationCapable: true,
      },
    ],
    presets: [
      {
        id: "tempoLockDefault",
        name: "Studio Tempo",
        description: "Default tempo and groove settings for modern production.",
        parameterValues: { tempo: 124, swing: 12 },
      },
    ],
    routing: {
      source: "Host Clock",
      destination: "Transport",
      insertPoint: "Tempo Control",
      sends: [],
    },
    automationBindings: [
      {
        id: "tempoLockSwing",
        name: "Swing Control",
        parameterId: "swing",
        controlSource: "Macro",
        curve: "linear",
        range: { min: 0, max: 50 },
      },
    ],
    bridgeSupport: true,
  },
  {
    id: "bridgeSync",
    name: "BridgeSync",
    vendor: "BridgeWorks",
    category: "utility",
    description:
      "Host bridge adapter for syncing plugin chains between Ableton and FL Studio.",
    hostSupport: ["Ableton", "FL Studio"],
    defaultPresetId: "bridgeSyncDefault",
    parameters: [
      {
        id: "bufferSize",
        name: "Buffer Size",
        min: 64,
        max: 1024,
        default: 256,
        unit: "samples",
        automationCapable: false,
      },
      {
        id: "latencyComp",
        name: "Latency Compensation",
        min: 0,
        max: 200,
        default: 32,
        unit: "ms",
        automationCapable: false,
      },
    ],
    presets: [
      {
        id: "bridgeSyncDefault",
        name: "Bridge Default",
        description: "Default bridge settings for cross-DAW compatibility.",
        parameterValues: { bufferSize: 256, latencyComp: 32 },
      },
    ],
    routing: {
      source: "Host Bridge",
      destination: "DAW Session",
      insertPoint: "Bridge Path",
      sends: [],
    },
    automationBindings: [],
    bridgeSupport: true,
  },
];
